### PR TITLE
Restore plot, use UnicodePlots

### PR DESCRIPTION
**Pull request by t-bltg**
For plotting using `Plots` in a CI environment whithout any display, you can use the [`UnicodePlots` backend](https://docs.juliaplots.org/latest/backends/#[UnicodePlots](https://github.com/Evizero/UnicodePlots.jl)) which only uses Julia internally and is robust.

### CODE REVIEW

**Comment by jverzani** [comment]
That's such a good idea. Not sure why I hadn't figured that out!

**Comment by t-bltg** [comment]
With the recent additions that I've made, you can even use subplots in a grid layout :wink: .

Here the first `Legendre` Polynomials:
Legendre

**Comment by jverzani** [comment]
Did you want to add that layout to an example? It would be a nice addition.

**Comment by t-bltg** [comment]
> Did you want to add that layout to an example? It would be a nice addition.

It's just that I'm into `Legendre` polynomials atm (`DG` methods), if you want it, I can do that ;)

**Comment by t-bltg** [comment]
There you go, PR updated.

Note that for `UnicodePlots`, you must use:
- `show(current())` at the end of the example;
- use `ansicolor=true` in `Documenter`'s `makedocs()` (see [here](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.HTML)).

**Comment by jverzani** [comment]
thanks again!

**Pull request merged**
